import Charts
import Observation
import PhotosUI
import SwiftData
import SwiftUI
import UIKit
import WidgetKit

struct ProfileEditor: View {
    @EnvironmentObject private var purchaseManager: PurchaseManager
    @Bindable var profile: HairProfile
    let entries: [CheckInEntry]
    let tasks: [RoutineTask]
    let triggerEvents: [HairTriggerEvent]
    let medications: [MedicationLog]
    let procedureEvents: [ProcedureEvent]
    let labResults: [LabResultEntry]
    let photoRecords: [PhotoRecord]
    @State private var isPresentingOnboardingUpdate = false
    @State private var isPresentingPremiumPaywall = false

    private let textureOptions = ["Straight 1A-1C", "Wavy 2A-2C", "Wavy 2C / 3A", "Curly 3A-3C", "Coily 4A-4C"]
    private let sensitivityOptions = ["Balanced", "Dry", "Oily", "Sensitive", "Flaky"]
    private let goalOptions = ["Length retention", "Stronger roots", "Hydration", "Reduce shedding", "Scalp balance"]
    private let hairLossFocusOptions = HairLossFocus.allCases.map(\.rawValue)

    // Emits plain Form sections; ProfileTab owns the containing Form so these
    // rows scroll together with the profile header.
    var body: some View {
        Group {
            Section("Profile") {
                TextField("Name", text: $profile.name)
                Picker("Texture", selection: $profile.texture) {
                    ForEach(textureOptions, id: \.self) { option in
                        Text(option).tag(option)
                    }
                }
                Picker("Primary Goal", selection: $profile.primaryGoal) {
                    ForEach(goalOptions, id: \.self) { option in
                        Text(option).tag(option)
                    }
                }
                Picker("Tracking Focus", selection: $profile.hairLossFocus) {
                    ForEach(hairLossFocusOptions, id: \.self) { option in
                        Text(option).tag(option)
                    }
                }
                TextField("Pattern distribution", text: $profile.patternDistribution)
                TextField("Family history", text: $profile.familyHistorySummary)
            }

            Section("Routine Preferences") {
                Stepper("Wash every \(profile.washFrequencyDays) day\(profile.washFrequencyDays == 1 ? "" : "s")", value: $profile.washFrequencyDays, in: 1...10)
                Stepper("Preferred wash hour: \(formattedHour(profile.preferredWashHour))", value: $profile.preferredWashHour, in: 0...23)
                Picker("Scalp Sensitivity", selection: $profile.scalpSensitivity) {
                    ForEach(sensitivityOptions, id: \.self) { option in
                        Text(option).tag(option)
                    }
                }
            }

            Section("Notes") {
                TextField("What are you observing lately?", text: $profile.notes, axis: .vertical)
                    .lineLimit(4...8)
            }

            Section("Quick Stats") {
                statRow(label: "Check-ins logged", value: "\(entries.count)")
                statRow(label: "Routine tasks", value: "\(tasks.count)")
                statRow(label: "Trigger events", value: "\(triggerEvents.count)")
                statRow(label: "Current streak", value: "\(HairInsightCalculator.currentStreak(for: entries)) days")
            }

            Section("Plan") {
                Button {
                    isPresentingOnboardingUpdate = true
                } label: {
                    Label("Update Onboarding Plan", systemImage: "slider.horizontal.3")
                }

                Text("Use this when your scalp pattern, styling habits, medication status, or tracking goals change. The app will replace its previous autogenerated onboarding items.")
                    .font(.system(size: 13, weight: .medium, design: .rounded))
                    .foregroundStyle(.secondary)
            }
            .fullScreenCover(isPresented: $isPresentingOnboardingUpdate) {
                OnboardingSurveyView(profile: profile, mode: .update)
            }

            Section("Clinician Export") {
                if purchaseManager.hasPremiumAccess {
                    ShareLink(
                        item: ClinicianExportService.buildText(
                            profile: profile,
                            entries: entries,
                            tasks: tasks,
                            medications: medications,
                            procedures: procedureEvents,
                            labs: labResults,
                            triggers: triggerEvents,
                            photoRecords: photoRecords
                        ),
                        subject: Text("Hair Compass Summary"),
                        message: Text("Timeline summary for clinician review.")
                    ) {
                        Label("Share Clinician Summary", systemImage: "square.and.arrow.up")
                    }
                } else {
                    Button {
                        isPresentingPremiumPaywall = true
                    } label: {
                        Label("Unlock Clinician Summary", systemImage: "lock.fill")
                    }
                }

                Text("Exports profile context, recent check-ins, routine, medications, procedures, labs, triggers, and standardized photo notes in one concise summary.")
                    .font(.system(size: 13, weight: .medium, design: .rounded))
                    .foregroundStyle(.secondary)
            }
            .sheet(isPresented: $isPresentingPremiumPaywall) {
                PremiumPaywallView()
            }

            Section("Privacy & Support") {
                if let privacyURL = AppSubmissionLinks.privacyPolicyURL {
                    Link(destination: privacyURL) {
                        Label("Privacy Policy", systemImage: "hand.raised.fill")
                    }
                } else {
                    Label("Privacy Policy URL needed before submission", systemImage: "exclamationmark.triangle.fill")
                        .foregroundStyle(Color.orange)
                }

                if let supportURL = AppSubmissionLinks.supportURL {
                    Link(destination: supportURL) {
                        Label("Support", systemImage: "questionmark.circle.fill")
                    }
                } else {
                    Label("Support URL needed before submission", systemImage: "exclamationmark.triangle.fill")
                        .foregroundStyle(Color.orange)
                }

                Text("Review this app’s privacy policy before using HealthKit, camera, photos, AI analysis, subscriptions, or affiliate links.")
                    .font(.system(size: 13, weight: .medium, design: .rounded))
                    .foregroundStyle(.secondary)
            }
        }
    }

    private func formattedHour(_ hour: Int) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "h a"

        var components = DateComponents()
        components.hour = hour
        components.minute = 0
        let date = Calendar.current.date(from: components) ?? .now
        return formatter.string(from: date)
    }

    private func statRow(label: String, value: String) -> some View {
        HStack {
            Text(label)
            Spacer()
            Text(value)
                .foregroundStyle(.secondary)
        }
    }
}

// MARK: - Log Shedding Modal (Design Spec 4.6)

struct LogSheddingModal: View {
    @Environment(\.dismiss) private var dismiss
    let averageShedding: Int
    let onSave: (Int, Set<String>) -> Void

    @State private var sheddingCount: Int = 47
    @State private var selectedTriggers: Set<String> = []
    @State private var saveAnimation = false

    private let triggerOptions = [
        "High stress", "Poor sleep", "Tight style",
        "New product", "Illness", "Travel"
    ]

    var body: some View {
        ZStack {
            // Pearl→Sand gradient background
            LinearGradient(
                colors: [PremiumTheme.pearl, PremiumTheme.sand.opacity(0.6)],
                startPoint: .top,
                endPoint: .bottom
            )
            .ignoresSafeArea()

            VStack(spacing: 24) {
                // Handle bar
                RoundedRectangle(cornerRadius: 2)
                    .fill(PremiumTheme.sand)
                    .frame(width: 44, height: 4)
                    .padding(.top, 14)

                // Eyebrow
                Text("LOG · POST-SHOWER")
                    .font(.system(size: 11, weight: .bold, design: .monospaced))
                    .tracking(2.0)
                    .foregroundStyle(PremiumTheme.gold)

                // Title
                Text("How much shedding today?")
                    .font(.system(size: 22, weight: .bold, design: .serif))
                    .foregroundStyle(PremiumTheme.ink)
                    .multilineTextAlignment(.center)

                // Number reel
                VStack(spacing: 6) {
                    HStack(alignment: .firstTextBaseline, spacing: 2) {
                        Text("\(sheddingCount)")
                            .font(.system(size: 84, weight: .bold, design: .serif))
                            .foregroundStyle(PremiumTheme.forest)
                            .contentTransition(.numericText())
                            .animation(.spring(response: 0.3, dampingFraction: 0.8), value: sheddingCount)
                    }

                    Text("STRANDS")
                        .font(.system(size: 11, weight: .bold, design: .monospaced))
                        .tracking(2.5)
                        .foregroundStyle(PremiumTheme.mutedInk)
                }

                // Stepper controls
                HStack(spacing: 20) {
                    Button {
                        if sheddingCount > 0 {
                            sheddingCount -= 5
                            HapticHelper.light()
                        }
                    } label: {
                        Image(systemName: "minus")
                            .font(.system(size: 18, weight: .bold))
                            .foregroundStyle(PremiumTheme.forest)
                            .frame(width: 48, height: 48)
                            .background(PremiumTheme.forest.opacity(0.10), in: Circle())
                    }
                    .buttonStyle(.plain)

                    // Slider
                    Slider(value: Binding(
                        get: { Double(sheddingCount) },
                        set: { sheddingCount = Int($0) }
                    ), in: 0...200, step: 1)
                    .tint(PremiumTheme.forest)

                    Button {
                        if sheddingCount < 200 {
                            sheddingCount += 5
                            HapticHelper.light()
                        }
                    } label: {
                        Image(systemName: "plus")
                            .font(.system(size: 18, weight: .bold))
                            .foregroundStyle(PremiumTheme.forest)
                            .frame(width: 48, height: 48)
                            .background(PremiumTheme.forest.opacity(0.10), in: Circle())
                    }
                    .buttonStyle(.plain)
                }
                .padding(.horizontal, 8)

                // Reference band
                logReferenceBand

                // Trigger chips
                VStack(alignment: .leading, spacing: 10) {
                    Text("TRIGGERS")
                        .font(.system(size: 10, weight: .bold, design: .monospaced))
                        .tracking(1.8)
                        .foregroundStyle(PremiumTheme.mutedInk)

                    FlowLayout(spacing: 8) {
                        ForEach(triggerOptions, id: \.self) { trigger in
                            let isSelected = selectedTriggers.contains(trigger)
                            Button {
                                withAnimation(.spring(response: 0.25, dampingFraction: 0.82)) {
                                    if isSelected {
                                        selectedTriggers.remove(trigger)
                                    } else {
                                        selectedTriggers.insert(trigger)
                                    }
                                }
                                HapticHelper.selection()
                            } label: {
                                Text(trigger)
                                    .font(.system(size: 13, weight: isSelected ? .bold : .medium))
                                    .foregroundStyle(isSelected ? .white : PremiumTheme.ink)
                                    .padding(.horizontal, 14)
                                    .padding(.vertical, 8)
                                    .background(
                                        isSelected
                                            ? AnyShapeStyle(PremiumTheme.forestTealGradient)
                                            : AnyShapeStyle(Color.white.opacity(0.80)),
                                        in: Capsule()
                                    )
                                    .overlay(
                                        Capsule()
                                            .stroke(
                                                isSelected ? Color.clear : PremiumTheme.forest.opacity(0.12),
                                                lineWidth: 1
                                            )
                                    )
                            }
                            .buttonStyle(.plain)
                        }
                    }
                }
                .padding(.horizontal, 4)

                Spacer()

                // Save CTA
                Button {
                    saveAnimation = true
                    let mapped = mapSheddingCountToLevel(sheddingCount)
                    onSave(mapped, selectedTriggers)
                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) {
                        dismiss()
                    }
                } label: {
                    HStack(spacing: 8) {
                        Image(systemName: "checkmark")
                            .font(.system(size: 14, weight: .bold))
                        Text("Save Log")
                            .font(.system(size: 16, weight: .bold))
                    }
                    .foregroundStyle(.white)
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 16)
                    .background(PremiumTheme.forestTealGradient, in: RoundedRectangle(cornerRadius: 20, style: .continuous))
                    .shadow(color: PremiumTheme.forest.opacity(0.25), radius: 12, y: 6)
                    .scaleEffect(saveAnimation ? 0.96 : 1.0)
                    .animation(.spring(response: 0.25, dampingFraction: 0.6), value: saveAnimation)
                }
                .buttonStyle(.plain)
                .padding(.bottom, 16)
            }
            .padding(.horizontal, 20)
        }
        .onAppear {
            // Set initial count near the user's average
            sheddingCount = max(10, averageShedding > 0 ? averageShedding : 47)
        }
    }

    private var logReferenceBand: some View {
        VStack(spacing: 6) {
            GeometryReader { geo in
                let width = geo.size.width
                ZStack(alignment: .leading) {
                    // Gradient band: teal→gold→rust
                    RoundedRectangle(cornerRadius: 5)
                        .fill(
                            LinearGradient(
                                colors: [
                                    PremiumTheme.teal,
                                    PremiumTheme.gold,
                                    Color(red: 0.75, green: 0.35, blue: 0.25)
                                ],
                                startPoint: .leading,
                                endPoint: .trailing
                            )
                        )
                        .frame(height: 10)

                    // Position marker
                    let fraction = min(CGFloat(sheddingCount) / 200.0, 1.0)
                    Circle()
                        .fill(Color.white)
                        .frame(width: 16, height: 16)
                        .shadow(color: .black.opacity(0.2), radius: 4, y: 2)
                        .offset(x: fraction * (width - 16))
                        .animation(.spring(response: 0.3, dampingFraction: 0.8), value: sheddingCount)
                }
            }
            .frame(height: 16)

            HStack {
                Text("LOW")
                    .font(.system(size: 9, weight: .bold, design: .monospaced))
                    .foregroundStyle(PremiumTheme.teal)
                Spacer()
                Text("MODERATE")
                    .font(.system(size: 9, weight: .bold, design: .monospaced))
                    .foregroundStyle(PremiumTheme.gold)
                Spacer()
                Text("HIGH")
                    .font(.system(size: 9, weight: .bold, design: .monospaced))
                    .foregroundStyle(Color(red: 0.75, green: 0.35, blue: 0.25))
            }
        }
        .padding(.horizontal, 4)
    }

    private func mapSheddingCountToLevel(_ count: Int) -> Int {
        // Map strand count (0-200) to the app's 0-100 shedding level scale
        switch count {
        case 0...20: return 10
        case 21...40: return 25
        case 41...60: return 40
        case 61...80: return 55
        case 81...100: return 65
        case 101...130: return 75
        case 131...160: return 85
        default: return 95
        }
    }
}

// Simple flow layout for trigger chips
struct FlowLayout: Layout {
    var spacing: CGFloat = 8

    func sizeThatFits(proposal: ProposedViewSize, subviews: Subviews, cache: inout ()) -> CGSize {
        let containerWidth = proposal.width ?? .infinity
        var currentX: CGFloat = 0
        var currentY: CGFloat = 0
        var lineHeight: CGFloat = 0

        for subview in subviews {
            let size = subview.sizeThatFits(.unspecified)
            if currentX + size.width > containerWidth && currentX > 0 {
                currentX = 0
                currentY += lineHeight + spacing
                lineHeight = 0
            }
            lineHeight = max(lineHeight, size.height)
            currentX += size.width + spacing
        }

        return CGSize(width: containerWidth, height: currentY + lineHeight)
    }

    func placeSubviews(in bounds: CGRect, proposal: ProposedViewSize, subviews: Subviews, cache: inout ()) {
        var currentX: CGFloat = bounds.minX
        var currentY: CGFloat = bounds.minY
        var lineHeight: CGFloat = 0

        for subview in subviews {
            let size = subview.sizeThatFits(.unspecified)
            if currentX + size.width > bounds.maxX && currentX > bounds.minX {
                currentX = bounds.minX
                currentY += lineHeight + spacing
                lineHeight = 0
            }
            subview.place(at: CGPoint(x: currentX, y: currentY), proposal: .unspecified)
            lineHeight = max(lineHeight, size.height)
            currentX += size.width + spacing
        }
    }
}

struct AddCheckInSheet: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(\.modelContext) private var modelContext

    @State private var date = Date()
    @State private var scalpScore = 80.0
    @State private var hydrationScore = 80.0
    @State private var sheddingLevel = 20.0
    @State private var stressLevel = 20.0
    @State private var hasItch = false
    @State private var hasFlaking = false
    @State private var hasScalpPain = false
    @State private var hasPatchyHairLoss = false
    @State private var hasTightStyleTension = false
    @State private var isWashDay = false
    @State private var note = ""
    @State private var checkInPhoto: UIImage?
    @State private var photoPickerItem: PhotosPickerItem?
    @State private var isShowingCamera = false
    @State private var photoNote = ""

    var body: some View {
        NavigationStack {
            ZStack {
                appBackground.ignoresSafeArea()

                ScrollView(showsIndicators: false) {
                    VStack(alignment: .leading, spacing: 20) {
                        VStack(alignment: .leading, spacing: 12) {
                            HStack(spacing: 14) {
                                Image(systemName: "waveform.path.ecg")
                                    .font(.system(size: 22, weight: .bold))
                                    .foregroundStyle(.white)
                                    .frame(width: 48, height: 48)
                                    .background(Color(red: 0.22, green: 0.38, blue: 0.67), in: RoundedRectangle(cornerRadius: 14, style: .continuous))
                                    .shadow(color: Color(red: 0.22, green: 0.38, blue: 0.67).opacity(0.35), radius: 8, y: 4)

                                VStack(alignment: .leading, spacing: 3) {
                                    Text("New Check-In")
                                        .font(.system(size: 26, weight: .heavy, design: .rounded))
                                        .foregroundStyle(Color(red: 0.12, green: 0.16, blue: 0.14))
                                    Text("Quick level cards for today")
                                        .font(.system(size: 13, weight: .medium, design: .rounded))
                                        .foregroundStyle(Color(red: 0.43, green: 0.50, blue: 0.46))
                                }
                            }
                        }
                        .cardStyle()

                        VStack(alignment: .leading, spacing: 14) {
                            Text("Date")
                                .font(.system(size: 18, weight: .bold, design: .rounded))
                            DatePicker("Check-In Date", selection: $date)
                                .labelsHidden()
                                .datePickerStyle(.compact)
                                .padding(.horizontal, 14)
                                .padding(.vertical, 12)
                                .background(Color.white.opacity(0.88), in: RoundedRectangle(cornerRadius: 18, style: .continuous))
                        }
                        .cardStyle()

                        CheckInMetricSelector(
                            title: "Scalp Condition",
                            subtitle: "Pick the level that best matches how your scalp feels.",
                            icon: "aqi.medium",
                            tint: Color(red: 0.35, green: 0.57, blue: 0.44),
                            selection: $scalpScore,
                            levels: [
                                MetricLevel(value: 20, title: "Irritated", detail: "Red, sore, reactive", imageName: "metric-scalp-low"),
                                MetricLevel(value: 40, title: "Sensitive", detail: "Tight or uneasy", imageName: "metric-scalp-low"),
                                MetricLevel(value: 60, title: "Mixed", detail: "Some calm, some dry", imageName: "metric-scalp-mid"),
                                MetricLevel(value: 80, title: "Balanced", detail: "Comfortable and settled", imageName: "metric-scalp-high"),
                                MetricLevel(value: 100, title: "Excellent", detail: "Calm, clean, happy", imageName: "metric-scalp-high")
                            ]
                        )

                        CheckInMetricSelector(
                            title: "Hydration",
                            subtitle: "Choose how hydrated the scalp and hair feel right now.",
                            icon: "drop.fill",
                            tint: Color(red: 0.24, green: 0.49, blue: 0.81),
                            selection: $hydrationScore,
                            levels: [
                                MetricLevel(value: 20, title: "Parched", detail: "Very dry and rough", imageName: "metric-hydration-low"),
                                MetricLevel(value: 40, title: "Dry", detail: "Needs moisture soon", imageName: "metric-hydration-low"),
                                MetricLevel(value: 60, title: "Okay", detail: "Not bad, not plush", imageName: "metric-hydration-mid"),
                                MetricLevel(value: 80, title: "Hydrated", detail: "Soft and comfortable", imageName: "metric-hydration-high"),
                                MetricLevel(value: 100, title: "Plush", detail: "Very moisturized", imageName: "metric-hydration-high")
                            ]
                        )

                        CheckInMetricSelector(
                            title: "Shedding",
                            subtitle: "Estimate the amount of fallout you noticed today.",
                            icon: "wind",
                            tint: Color(red: 0.84, green: 0.56, blue: 0.28),
                            selection: $sheddingLevel,
                            levels: [
                                MetricLevel(value: 20, title: "Minimal", detail: "Barely noticeable", imageName: "metric-shedding-low"),
                                MetricLevel(value: 40, title: "Low", detail: "Small amount", imageName: "metric-shedding-low"),
                                MetricLevel(value: 60, title: "Moderate", detail: "More than usual", imageName: "metric-shedding-mid"),
                                MetricLevel(value: 80, title: "High", detail: "Noticeable fallout", imageName: "metric-shedding-high"),
                                MetricLevel(value: 100, title: "Heavy", detail: "Concerning amount", imageName: "metric-shedding-high")
                            ]
                        )

                        CheckInMetricSelector(
                            title: "Stress",
                            subtitle: "Pick the level that best matches your overall day.",
                            icon: "brain.head.profile",
                            tint: Color(red: 0.63, green: 0.39, blue: 0.73),
                            selection: $stressLevel,
                            levels: [
                                MetricLevel(value: 20, title: "Calm", detail: "Relaxed and steady", imageName: "metric-stress-low"),
                                MetricLevel(value: 40, title: "Light", detail: "Slightly busy", imageName: "metric-stress-low"),
                                MetricLevel(value: 60, title: "Medium", detail: "Mentally full", imageName: "metric-stress-mid"),
                                MetricLevel(value: 80, title: "High", detail: "A lot going on", imageName: "metric-stress-high"),
                                MetricLevel(value: 100, title: "Overloaded", detail: "Very stressed", imageName: "metric-stress-high")
                            ]
                        )

                        VStack(alignment: .leading, spacing: 14) {
                            Text("Observed Symptoms")
                                .font(.system(size: 20, weight: .bold, design: .rounded))

                            LazyVGrid(columns: [GridItem(.flexible()), GridItem(.flexible())], spacing: 12) {
                                SymptomToggleCard(title: "Itch", systemImage: "hand.tap.fill", isOn: $hasItch)
                                SymptomToggleCard(title: "Flaking", systemImage: "sparkles.rectangle.stack.fill", isOn: $hasFlaking)
                                SymptomToggleCard(title: "Pain or Burning", systemImage: "flame.fill", isOn: $hasScalpPain)
                                SymptomToggleCard(title: "Patchy Loss", systemImage: "circle.grid.2x2.fill", isOn: $hasPatchyHairLoss)
                                SymptomToggleCard(title: "Tight Tension", systemImage: "arrow.left.and.right.righttriangle.left.righttriangle.right.fill", isOn: $hasTightStyleTension)
                            }
                        }
                        .cardStyle()

                        SymptomToggleCard(title: "Wash Day", systemImage: "drop.fill", isOn: $isWashDay)
                            .cardStyle()

                        VStack(alignment: .leading, spacing: 12) {
                            Text("Photo Of The Day")
                                .font(.system(size: 20, weight: .bold, design: .rounded))

                            Text("Add one reference photo with the check-in so the day’s notes and image stay together.")
                                .font(.system(size: 14, weight: .medium, design: .rounded))
                                .foregroundStyle(Color(red: 0.38, green: 0.44, blue: 0.40))

                            VStack(alignment: .leading, spacing: 8) {
                                standardizationLine("Use the same angle and camera distance each time.")
                                standardizationLine("Keep lighting and hair parting consistent.")
                                standardizationLine("Log whether hair is wet, damp, or dry in the note.")
                                standardizationLine("Compare on a fixed interval, not every random day.")
                            }
                            .padding(14)
                            .background(Color.white.opacity(0.62), in: RoundedRectangle(cornerRadius: 18, style: .continuous))

                            if let checkInPhoto {
                                Image(uiImage: checkInPhoto)
                                    .resizable()
                                    .scaledToFill()
                                    .frame(height: 190)
                                    .clipShape(RoundedRectangle(cornerRadius: 20, style: .continuous))
                            } else {
                                RoundedRectangle(cornerRadius: 20, style: .continuous)
                                    .fill(Color.white.opacity(0.78))
                                    .frame(height: 130)
                                    .overlay(
                                        VStack(spacing: 8) {
                                            Image(systemName: "camera.macro")
                                                .font(.system(size: 24, weight: .bold))
                                                .foregroundStyle(Color(red: 0.20, green: 0.47, blue: 0.79))
                                            Text("No check-in photo yet")
                                                .font(.system(size: 14, weight: .semibold, design: .rounded))
                                                .foregroundStyle(.secondary)
                                        }
                                    )
                            }

                            HStack {
                                Button {
                                    isShowingCamera = true
                                } label: {
                                    Label("Camera", systemImage: "camera")
                                }
                                .buttonStyle(.borderedProminent)

                                PhotosPicker(selection: $photoPickerItem, matching: .images) {
                                    Label("Library", systemImage: "photo")
                                }
                                .buttonStyle(.bordered)
                            }

                            TextField("Photo note (optional)", text: $photoNote)
                                .padding(14)
                                .background(Color.white.opacity(0.88), in: RoundedRectangle(cornerRadius: 18, style: .continuous))
                        }
                        .cardStyle()

                        VStack(alignment: .leading, spacing: 12) {
                            Text("Notes")
                                .font(.system(size: 20, weight: .bold, design: .rounded))
                            TextField("Products used, styling, wash day, anything unusual…", text: $note, axis: .vertical)
                                .lineLimit(4...8)
                                .padding(14)
                                .background(Color.white.opacity(0.88), in: RoundedRectangle(cornerRadius: 18, style: .continuous))
                        }
                        .cardStyle()

                        Button {
                            saveCheckIn()
                        } label: {
                            HStack(spacing: 10) {
                                Image(systemName: "checkmark.circle.fill")
                                Text("Save Check-In")
                            }
                            .font(.system(size: 17, weight: .bold, design: .rounded))
                            .foregroundStyle(.white)
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 16)
                            .background(
                                LinearGradient(
                                    colors: [
                                        Color(red: 0.24, green: 0.42, blue: 0.39),
                                        Color(red: 0.16, green: 0.30, blue: 0.28)
                                    ],
                                    startPoint: .leading,
                                    endPoint: .trailing
                                ),
                                in: RoundedRectangle(cornerRadius: 20, style: .continuous)
                            )
                            .shadow(color: Color(red: 0.16, green: 0.30, blue: 0.28).opacity(0.3), radius: 12, y: 6)
                        }
                        .buttonStyle(.plain)
                    }
                    .padding(20)
                }
            }
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") {
                        saveCheckIn()
                    }
                }
            }
        }
        .sheet(isPresented: $isShowingCamera) {
            CameraCaptureView { image in
                checkInPhoto = image
                isShowingCamera = false
            }
        }
        .task(id: photoPickerItem) {
            guard let photoPickerItem else { return }
            if let data = try? await photoPickerItem.loadTransferable(type: Data.self),
               let image = UIImage(data: data) {
                checkInPhoto = image
            }
            self.photoPickerItem = nil
        }
    }

    private func saveCheckIn() {
        HapticHelper.success()
        let observation = dailyObservation(for: date)
        let entry = CheckInEntry(
            date: date,
            scalpScore: Int(scalpScore.rounded()),
            hydrationScore: Int(hydrationScore.rounded()),
            sheddingLevel: Int(sheddingLevel.rounded()),
            stressLevel: Int(stressLevel.rounded()),
            hasItch: hasItch,
            hasFlaking: hasFlaking,
            hasScalpPain: hasScalpPain,
            hasPatchyHairLoss: hasPatchyHairLoss,
            hasTightStyleTension: hasTightStyleTension,
            isWashDay: isWashDay,
            note: note.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? "Quick check-in logged." : note,
            dailyObservation: observation
        )
        observation.summary = checkInSummary(for: entry)
        modelContext.insert(entry)
        savePhotoRecordIfNeeded(for: entry, observation: observation)
        dismiss()
    }

    private func savePhotoRecordIfNeeded(for entry: CheckInEntry, observation: DailyObservation) {
        guard let checkInPhoto else { return }

        do {
            let dayStart = Calendar.current.startOfDay(for: date)
            let nextDay = Calendar.current.date(byAdding: .day, value: 1, to: dayStart) ?? dayStart
            let descriptor = FetchDescriptor<PhotoRecord>(
                predicate: #Predicate<PhotoRecord> {
                    $0.checkIn != nil && $0.createdAt >= dayStart && $0.createdAt < nextDay
                }
            )
            let existingRecords = try modelContext.fetch(descriptor)
            existingRecords.forEach(modelContext.delete)

            let path = try PhotoFileStore.shared.save(image: checkInPhoto)
            let record = PhotoRecord(
                createdAt: date,
                sessionTitle: "Check-In \(date.formatted(date: .abbreviated, time: .omitted))",
                angle: "Check-In",
                imagePath: path,
                notes: photoNote.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? note : photoNote,
                checkIn: entry,
                dailyObservation: observation
            )
            modelContext.insert(record)
        } catch {
            return
        }
    }

    private func dailyObservation(for date: Date) -> DailyObservation {
        let dayStart = Calendar.current.startOfDay(for: date)
        let nextDay = Calendar.current.date(byAdding: .day, value: 1, to: dayStart) ?? dayStart
        let descriptor = FetchDescriptor<DailyObservation>(
            predicate: #Predicate<DailyObservation> {
                $0.date >= dayStart && $0.date < nextDay
            }
        )

        if let observation = try? modelContext.fetch(descriptor).first {
            return observation
        }

        let observation = DailyObservation(date: dayStart)
        modelContext.insert(observation)
        return observation
    }

    private func checkInSummary(for entry: CheckInEntry) -> String {
        "Check-in logged with scalp \(entry.scalpScore), hydration \(entry.hydrationScore), shedding \(entry.sheddingLevel), and stress \(entry.stressLevel)."
    }

    private func standardizationLine(_ text: String) -> some View {
        HStack(alignment: .top, spacing: 8) {
            Image(systemName: "camera.aperture")
                .foregroundStyle(Color(red: 0.20, green: 0.47, blue: 0.79))
                .padding(.top, 2)
            Text(text)
                .font(.system(size: 12, weight: .semibold, design: .rounded))
                .foregroundStyle(Color(red: 0.33, green: 0.39, blue: 0.35))
        }
    }
}

struct AddTaskSheet: View {
    @Environment(\.dismiss) private var dismiss
    @Environment(\.modelContext) private var modelContext
    @EnvironmentObject private var purchaseManager: PurchaseManager
    @AppStorage("openAIAPIKey") private var openAIAPIKey = ""
    let profile: HairProfile?

    @State private var title = ""
    @State private var itemType: RoutineItemType = .product
    @State private var detail = ""
    @State private var timeLabel = "20:00"
    @State private var weekday = Calendar.current.component(.weekday, from: .now)
    @State private var category = "Scalp"
    @State private var recurrenceType: RoutineRecurrenceType = .weekly
    @State private var recurrenceInterval = 2
    @State private var startDate = Date()
    @State private var selectedWeekdays: Set<Int> = [Calendar.current.component(.weekday, from: .now)]
    @State private var productPhoto: UIImage?
    @State private var photoPickerItem: PhotosPickerItem?
    @State private var isShowingCamera = false
    @State private var isAnalyzingProduct = false
    @State private var productAnalysis: RoutineProductAnalysis?
    @State private var analysisErrorMessage = ""
    @State private var isPresentingPremiumPaywall = false

    private let categories = ["Scalp", "Hydration", "Wash", "Protection", "Styling"]

    var body: some View {
        NavigationStack {
            ScrollView(showsIndicators: false) {
                VStack(alignment: .leading, spacing: 18) {
                    VStack(alignment: .leading, spacing: 8) {
                        Text("New Routine")
                            .font(.system(size: 34, weight: .bold, design: .rounded))
                            .foregroundStyle(Color(red: 0.15, green: 0.20, blue: 0.17))
                        Text("Add a product, habit, or technique with the same card-based feel as the rest of the app, then let Intelligence give a cautious usefulness read.")
                            .font(.system(size: 15, weight: .medium, design: .rounded))
                            .foregroundStyle(Color(red: 0.40, green: 0.46, blue: 0.43))
                    }

                    routineIdentityCard
                    routinePhotoCard
                    routineIntelligenceCard
                    routineScheduleCard
                }
                .padding(20)
            }
            .background(appBackground)
            .navigationTitle("New Routine Task")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") {
                        let productImagePath = saveProductPhotoIfNeeded()
                        let task = RoutineTask(
                            title: title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? "New routine task" : title,
                            itemType: itemType.rawValue,
                            detail: detail.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? "No extra details yet." : detail,
                            timeLabel: timeLabel,
                            weekday: weekday,
                            category: category,
                            productImagePath: productImagePath,
                            intelligenceScore: productAnalysis?.score ?? 0,
                            intelligenceSummary: productAnalysis?.summary ?? "",
                            recurrenceType: recurrenceType.rawValue,
                            recurrenceInterval: recurrenceType == .everyNDays ? recurrenceInterval : 1,
                            recurrenceWeekdays: recurrenceType == .weekly ? selectedWeekdays.sorted().map(String.init).joined(separator: ",") : "",
                            startDate: startDate
                        )
                        modelContext.insert(task)
                        dismiss()
                    }
                }
            }
        }
        .sheet(isPresented: $isShowingCamera) {
            CameraCaptureView { image in
                productPhoto = image
                isShowingCamera = false
            }
        }
        .sheet(isPresented: $isPresentingPremiumPaywall) {
            PremiumPaywallView()
        }
        .task(id: photoPickerItem) {
            guard let photoPickerItem else { return }
            if let data = try? await photoPickerItem.loadTransferable(type: Data.self),
               let image = UIImage(data: data) {
                productPhoto = image
            }
            self.photoPickerItem = nil
        }
    }

    private var weekdayPicker: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("Weekdays")
                .font(.system(size: 14, weight: .bold, design: .rounded))

            LazyVGrid(columns: [GridItem(.adaptive(minimum: 80), spacing: 8)], spacing: 8) {
                ForEach(1...7, id: \.self) { index in
                    let selected = selectedWeekdays.contains(index)
                    Button {
                        if selected {
                            selectedWeekdays.remove(index)
                        } else {
                            selectedWeekdays.insert(index)
                        }
                        weekday = selectedWeekdays.sorted().first ?? index
                    } label: {
                        Text(Calendar.current.weekdaySymbols[index - 1])
                            .font(.system(size: 12, weight: .bold, design: .rounded))
                            .frame(maxWidth: .infinity)
                            .padding(.vertical, 10)
                            .background(
                                selected ? Color(red: 0.20, green: 0.47, blue: 0.79) : Color.gray.opacity(0.12),
                                in: RoundedRectangle(cornerRadius: 12, style: .continuous)
                            )
                            .foregroundStyle(selected ? .white : Color.primary)
                    }
                    .buttonStyle(.plain)
                }
            }
        }
    }

    private var routineIdentityCard: some View {
        VStack(alignment: .leading, spacing: 14) {
            Text("What are you adding?")
                .font(.system(size: 20, weight: .bold, design: .rounded))

            TextField("Title", text: $title)
                .padding(14)
                .background(Color.white.opacity(0.88), in: RoundedRectangle(cornerRadius: 18, style: .continuous))

            VStack(alignment: .leading, spacing: 10) {
                Text("Type")
                    .font(.system(size: 14, weight: .bold, design: .rounded))
                    .foregroundStyle(Color(red: 0.38, green: 0.44, blue: 0.40))

                LazyVGrid(columns: [GridItem(.flexible()), GridItem(.flexible()), GridItem(.flexible())], spacing: 10) {
                    ForEach(RoutineItemType.allCases) { option in
                        routineOptionChip(
                            title: option.rawValue,
                            isSelected: itemType == option,
                            tint: itemTypeTint(for: option)
                        ) {
                            itemType = option
                        }
                    }
                }
            }

            VStack(alignment: .leading, spacing: 10) {
                Text("Category")
                    .font(.system(size: 14, weight: .bold, design: .rounded))
                    .foregroundStyle(Color(red: 0.38, green: 0.44, blue: 0.40))

                LazyVGrid(columns: [GridItem(.flexible()), GridItem(.flexible()), GridItem(.flexible())], spacing: 10) {
                    ForEach(categories, id: \.self) { option in
                        routineOptionChip(
                            title: option,
                            isSelected: category == option,
                            tint: categoryTint(for: option)
                        ) {
                            category = option
                        }
                    }
                }
            }

            VStack(alignment: .leading, spacing: 8) {
                Text("Notes or ingredients")
                    .font(.system(size: 14, weight: .bold, design: .rounded))
                    .foregroundStyle(Color(red: 0.38, green: 0.44, blue: 0.40))
                TextField("What is it, how will you use it, or what caught your eye?", text: $detail, axis: .vertical)
                    .lineLimit(3...6)
                    .padding(14)
                    .background(Color.white.opacity(0.88), in: RoundedRectangle(cornerRadius: 18, style: .continuous))
            }
        }
        .cardStyle()
    }

    private var routinePhotoCard: some View {
        VStack(alignment: .leading, spacing: 14) {
            Text("Product photo")
                .font(.system(size: 20, weight: .bold, design: .rounded))

            Group {
                if let productPhoto {
                    Image(uiImage: productPhoto)
                        .resizable()
                        .scaledToFill()
                } else {
                    RoundedRectangle(cornerRadius: 24, style: .continuous)
                        .fill(
                            LinearGradient(
                                colors: [
                                    Color.white.opacity(0.90),
                                    Color(red: 0.92, green: 0.96, blue: 0.98).opacity(0.86)
                                ],
                                startPoint: .topLeading,
                                endPoint: .bottomTrailing
                            )
                        )
                        .overlay(
                            VStack(spacing: 10) {
                                Image(systemName: "shippingbox.fill")
                                    .font(.system(size: 28, weight: .bold))
                                    .foregroundStyle(Color(red: 0.20, green: 0.47, blue: 0.79))
                                Text("Optional product photo")
                                    .font(.system(size: 16, weight: .bold, design: .rounded))
                                    .foregroundStyle(Color(red: 0.22, green: 0.28, blue: 0.26))
                                Text("A package front or ingredient panel can help the AI understand what kind of product this is.")
                                    .multilineTextAlignment(.center)
                                    .font(.system(size: 13, weight: .medium, design: .rounded))
                                    .foregroundStyle(Color(red: 0.43, green: 0.49, blue: 0.46))
                                    .padding(.horizontal, 20)
                            }
                        )
                }
            }
            .frame(height: 200)
            .clipShape(RoundedRectangle(cornerRadius: 24, style: .continuous))

            HStack(spacing: 10) {
                Button {
                    isShowingCamera = true
                } label: {
                    Label("Camera", systemImage: "camera")
                        .frame(maxWidth: .infinity)
                }
                .buttonStyle(.borderedProminent)
                .tint(Color(red: 0.20, green: 0.47, blue: 0.79))

                PhotosPicker(selection: $photoPickerItem, matching: .images) {
                    Label("Library", systemImage: "photo")
                        .frame(maxWidth: .infinity)
                }
                .buttonStyle(.bordered)
            }
        }
        .cardStyle()
    }

    private var routineIntelligenceCard: some View {
        VStack(alignment: .leading, spacing: 14) {
            HStack {
                VStack(alignment: .leading, spacing: 4) {
                    Text("AI usefulness read")
                        .font(.system(size: 20, weight: .bold, design: .rounded))
                    Text("A conservative product read for whether this likely adds meaningful value.")
                        .font(.system(size: 14, weight: .medium, design: .rounded))
                        .foregroundStyle(Color(red: 0.40, green: 0.46, blue: 0.43))
                }

                Spacer()

                Image(systemName: "sparkles.rectangle.stack.fill")
                    .font(.system(size: 24, weight: .bold))
                    .foregroundStyle(Color(red: 0.14, green: 0.37, blue: 0.54))
            }

            Button {
                if purchaseManager.hasPremiumAccess {
                    Task {
                        await analyzeProduct()
                    }
                } else {
                    isPresentingPremiumPaywall = true
                }
            } label: {
                HStack(spacing: 8) {
                    if purchaseManager.hasPremiumAccess && isAnalyzingProduct {
                        ProgressView()
                            .tint(.white)
                            .scaleEffect(0.85)
                    } else if purchaseManager.hasPremiumAccess {
                        Image(systemName: "wand.and.stars")
                    } else {
                        Image(systemName: "lock.fill")
                    }
                    Text(purchaseManager.hasPremiumAccess ? (productAnalysis == nil ? "Analyze With AI" : "Refresh AI Read") : "Unlock AI Read")
                }
                .font(.system(size: 14, weight: .bold, design: .rounded))
                .foregroundStyle(.white)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 14)
                .background(
                    LinearGradient(
                        colors: [
                            Color(red: 0.15, green: 0.39, blue: 0.56),
                            Color(red: 0.30, green: 0.56, blue: 0.73)
                        ],
                        startPoint: .topLeading,
                        endPoint: .bottomTrailing
                    ),
                    in: RoundedRectangle(cornerRadius: 18, style: .continuous)
                )
            }
            .buttonStyle(.plain)
            .disabled(purchaseManager.hasPremiumAccess && (isAnalyzingProduct || title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty || openAIAPIKey.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty))

            if let productAnalysis {
                aiUsefulnessCard(productAnalysis)
            } else {
                VStack(alignment: .leading, spacing: 8) {
                    Text("No read yet")
                        .font(.system(size: 15, weight: .bold, design: .rounded))
                        .foregroundStyle(Color(red: 0.19, green: 0.25, blue: 0.23))
                    Text("Intelligence can estimate whether a product is likely to help, is probably neutral, or looks mostly marketing-led. The read is guidance, not proof.")
                        .font(.system(size: 14, weight: .medium, design: .rounded))
                        .foregroundStyle(Color(red: 0.43, green: 0.49, blue: 0.46))
                }
                .padding(16)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(Color.white.opacity(0.82), in: RoundedRectangle(cornerRadius: 22, style: .continuous))
            }

            if !purchaseManager.hasPremiumAccess {
                Text("Hair Compass Pro unlocks AI usefulness reads for new routine items.")
                    .font(.system(size: 12, weight: .semibold, design: .rounded))
                    .foregroundStyle(Color(red: 0.76, green: 0.49, blue: 0.23))
            } else if openAIAPIKey.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                Text("Add your OpenAI API key from the Dashboard Intelligence card to enable product analysis. Product details and any attached product photo may be sent to OpenAI when this feature runs.")
                    .font(.system(size: 12, weight: .semibold, design: .rounded))
                    .foregroundStyle(Color(red: 0.76, green: 0.49, blue: 0.23))
            }

            if !analysisErrorMessage.isEmpty {
                Text(analysisErrorMessage)
                    .font(.system(size: 12, weight: .semibold, design: .rounded))
                    .foregroundStyle(Color(red: 0.68, green: 0.18, blue: 0.14))
            }
        }
        .cardStyle()
    }

    private var routineScheduleCard: some View {
        VStack(alignment: .leading, spacing: 14) {
            Text("Schedule")
                .font(.system(size: 20, weight: .bold, design: .rounded))

            TextField("Time", text: $timeLabel)
                .padding(14)
                .background(Color.white.opacity(0.88), in: RoundedRectangle(cornerRadius: 18, style: .continuous))

            Picker("Recurrence", selection: $recurrenceType) {
                ForEach(RoutineRecurrenceType.allCases) { option in
                    Text(option.rawValue).tag(option)
                }
            }
            .pickerStyle(.segmented)

            DatePicker("Starts", selection: $startDate, displayedComponents: .date)
                .datePickerStyle(.compact)
                .padding(14)
                .background(Color.white.opacity(0.88), in: RoundedRectangle(cornerRadius: 18, style: .continuous))

            if recurrenceType == .weekly {
                weekdayPicker
            }
            if recurrenceType == .everyNDays {
                Stepper("Every \(recurrenceInterval) days", value: $recurrenceInterval, in: 2...30)
            }
        }
        .cardStyle()
    }

    private func routineOptionChip(title: String, isSelected: Bool, tint: Color, action: @escaping () -> Void) -> some View {
        Button(action: action) {
            Text(title)
                .font(.system(size: 13, weight: .bold, design: .rounded))
                .foregroundStyle(isSelected ? .white : Color(red: 0.20, green: 0.24, blue: 0.22))
                .frame(maxWidth: .infinity)
                .padding(.vertical, 12)
                .background(
                    isSelected
                    ? LinearGradient(colors: [tint, tint.opacity(0.78)], startPoint: .topLeading, endPoint: .bottomTrailing)
                    : LinearGradient(colors: [Color.white.opacity(0.9), Color.white.opacity(0.74)], startPoint: .top, endPoint: .bottom),
                    in: RoundedRectangle(cornerRadius: 16, style: .continuous)
                )
        }
        .buttonStyle(.plain)
    }

    private func aiUsefulnessCard(_ analysis: RoutineProductAnalysis) -> some View {
        let tint = analysisTint(for: analysis.score)

        return VStack(alignment: .leading, spacing: 14) {
            HStack(alignment: .center, spacing: 14) {
                ZStack {
                    Circle()
                        .stroke(tint.opacity(0.18), lineWidth: 10)
                    Circle()
                        .trim(from: 0, to: CGFloat(analysis.score) / 100)
                        .stroke(
                            LinearGradient(colors: [tint, tint.opacity(0.6)], startPoint: .topLeading, endPoint: .bottomTrailing),
                            style: StrokeStyle(lineWidth: 10, lineCap: .round)
                        )
                        .rotationEffect(.degrees(-90))
                    VStack(spacing: 2) {
                        Text("\(analysis.score)")
                            .font(.system(size: 24, weight: .bold, design: .rounded))
                        Text("/100")
                            .font(.system(size: 11, weight: .bold, design: .rounded))
                            .foregroundStyle(Color(red: 0.42, green: 0.49, blue: 0.45))
                    }
                    .foregroundStyle(Color(red: 0.15, green: 0.21, blue: 0.18))
                }
                .frame(width: 92, height: 92)

                VStack(alignment: .leading, spacing: 8) {
                    Text(aiVerdict(for: analysis.score))
                        .font(.system(size: 18, weight: .bold, design: .rounded))
                        .foregroundStyle(Color(red: 0.15, green: 0.21, blue: 0.18))

                    Text(analysis.summary)
                        .font(.system(size: 14, weight: .medium, design: .rounded))
                        .foregroundStyle(Color(red: 0.39, green: 0.45, blue: 0.42))
                        .fixedSize(horizontal: false, vertical: true)

                    Text("\(analysis.confidence.capitalized) confidence")
                        .font(.system(size: 12, weight: .bold, design: .rounded))
                        .foregroundStyle(tint)
                        .padding(.horizontal, 10)
                        .padding(.vertical, 6)
                        .background(tint.opacity(0.12), in: Capsule())
                }
            }

            RoundedRectangle(cornerRadius: 999, style: .continuous)
                .fill(Color.white.opacity(0.88))
                .frame(height: 10)
                .overlay(alignment: .leading) {
                    RoundedRectangle(cornerRadius: 999, style: .continuous)
                        .fill(LinearGradient(colors: [tint, tint.opacity(0.55)], startPoint: .leading, endPoint: .trailing))
                        .frame(width: max(CGFloat(analysis.score) * 2.2, 24), height: 10)
                }
        }
        .padding(18)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            LinearGradient(
                colors: [
                    tint.opacity(0.14),
                    Color.white.opacity(0.84)
                ],
                startPoint: .topLeading,
                endPoint: .bottomTrailing
            ),
            in: RoundedRectangle(cornerRadius: 24, style: .continuous)
        )
        .overlay(
            RoundedRectangle(cornerRadius: 24, style: .continuous)
                .stroke(tint.opacity(0.18), lineWidth: 1)
        )
    }

    private func analysisTint(for score: Int) -> Color {
        switch score {
        case 70...100:
            return Color(red: 0.22, green: 0.58, blue: 0.42)
        case 40..<70:
            return Color(red: 0.85, green: 0.58, blue: 0.20)
        default:
            return Color(red: 0.76, green: 0.34, blue: 0.28)
        }
    }

    private func aiVerdict(for score: Int) -> String {
        switch score {
        case 70...100:
            return "Likely worth tracking"
        case 40..<70:
            return "Mixed value"
        default:
            return "Probably low value"
        }
    }

    private func itemTypeTint(for type: RoutineItemType) -> Color {
        switch type {
        case .product:
            return Color(red: 0.20, green: 0.47, blue: 0.79)
        case .habit:
            return Color(red: 0.28, green: 0.55, blue: 0.44)
        case .technique:
            return Color(red: 0.60, green: 0.42, blue: 0.72)
        case .device:
            return Color(red: 0.70, green: 0.46, blue: 0.24)
        case .supplement:
            return Color(red: 0.24, green: 0.56, blue: 0.42)
        }
    }

    private func categoryTint(for category: String) -> Color {
        switch category {
        case "Scalp":
            return Color(red: 0.28, green: 0.55, blue: 0.44)
        case "Hydration":
            return Color(red: 0.20, green: 0.47, blue: 0.79)
        case "Wash":
            return Color(red: 0.73, green: 0.53, blue: 0.26)
        case "Protection":
            return Color(red: 0.60, green: 0.42, blue: 0.72)
        default:
            return Color(red: 0.35, green: 0.40, blue: 0.37)
        }
    }

    @MainActor
    private func analyzeProduct() async {
        guard purchaseManager.hasPremiumAccess else {
            analysisErrorMessage = "Hair Compass Pro is required for AI product analysis."
            return
        }

        let trimmedKey = openAIAPIKey.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedKey.isEmpty else { return }

        isAnalyzingProduct = true
        analysisErrorMessage = ""

        defer { isAnalyzingProduct = false }

        do {
            productAnalysis = try await OpenAIRoutineProductAnalysisService(apiKey: trimmedKey).analyze(
                title: title,
                itemType: itemType.rawValue,
                category: category,
                notes: detail,
                image: productPhoto,
                profile: profile
            )
        } catch {
            analysisErrorMessage = error.localizedDescription
        }
    }

    private func saveProductPhotoIfNeeded() -> String {
        guard let productPhoto else { return "" }
        do {
            return try PhotoFileStore.shared.save(image: productPhoto)
        } catch {
            return ""
        }
    }
}

struct MetricLevel: Identifiable {
    let value: Double
    let title: String
    let detail: String
    let imageName: String

    var id: Double { value }
}

